CREATE TABLE IF NOT EXISTS  `UImages` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`storage` VARCHAR(50) NOT NULL,
	`name` VARCHAR(150) NULL DEFAULT NULL,
	`description` TEXT NULL,
	`type` VARCHAR(50) NULL DEFAULT NULL,
	`keywords` VARCHAR(150) NULL DEFAULT NULL,
	`stars` INT(11)  NULL DEFAULT NULL,
	`width` INT(11) NULL DEFAULT NULL,
	`height` INT(11) NULL DEFAULT NULL,
	`size` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;
